:recycle: 스크립트 수정

diff --git a/.husky/pre-commit b/.husky/pre-commit
--- a/.husky/pre-commit
+++ b/.husky/pre-commit
@@ -1,7 +1,14 @@
 #!/bin/sh
 
+branch="$(git rev-parse --abbrev-ref HEAD)"
+
+if [ "$branch" = "master" ]; then
+  echo "You can't commit directly to master branch"
+  exit 1
+fi
+
 . "$(dirname "$0")/_/husky.sh"
 
 npm run lint
-# npm run prettier
+npm run prettier
 # npm run test-ci
